export const UPDATE_LAT_LNG = "UPDATE_LAT_LNG";
export const UPDATE_LAST_SELECTED_POSITION = "UPDATE_LAST_SELECTED_POSITION";
export const RESET_LAST_SELECTED_POSITION = "RESET_LAST_SELECTED_POSITION"
