export const FETCH_TURBINE_DATA = "FETCH_TURBINE_DATA";
export const FETCH_WINDFARM_DATA = "FETCH_WINDFARM_DATA";
export const FETCH_JOB_DATA = "FETCH_JOB_DATA";

export const POST_ROW = "POST_ROW";
export const PATCH_ROW = "PATCH_ROW";
export const DELETE_ROW = "DELETE_ROW";

export const CREATE_JOB = "CREATE_JOB";
export const UPDATE_JOB_STATUS = "UPDATE_JOB_STATUS";
export const DELETE_JOB = "DELETE_JOB";
export const UPLOAD_CSV = "UPLOAD_CSV";
export const FETCH_LASTGANG_DATA = "FETCH_LASTGANG_DATA";
export const FETCH_INPUT_LIST = "FETCH_INPUT_LIST";

export const UPDATE_TABLE_FILTERS = "UPDATE_TABLE_FILTERS";
export const SET_PROPS_TABLE = "SET_PROPS_TABLE";

export const UPDATE_SELECTED_ROW_COORDINATES = "UPDATE_SELECTED_ROW_COORDINATES"